### ISSUE TITLE
Updates to allow non-orthorectified imagery

### ISSUE THREAD

**Issue by rddesmond** [DigitalGlobe/OpenSpaceNet#104]
OSN and it's use of Deepcore processing assumes that imagery is orthorectified (as in, bounded by lat and long lines).  Moving forward, this should be expanded to arbitrary images.  The training set should be assumed to operate with such distortion, and inference should take place in image space.  GDAL can be used to obtain the coordinates of the window from that pixel space.

**Comment by spvandermark** [comment]
Closed per @adpowel
